---
# Credentials for AAP
controller_credentials:
  - credential_type: Machine
    organization: Research & Development
    name: Vagrant
    description: This credential can be used with any Vagrant machine.
    inputs:
      username: vagrant
      ssh_key_data: "{{ lookup('file', '~/.vagrant.d/insecure_private_key') }}"
  - credential_type: Source Control
    name: Git
    description: General token for git
    inputs:
      username: git
      password: password
    organization: Research & Development
  - credential_type: Vault
    name: ansible-vault
    inputs:
      vault_password: s3cr3t
    description: Ansible Vault Password
    organization: Research & Development
